### PR TITLE
Support GitHub Actions

### PR DESCRIPTION
**Pull request by gorouflex**

### CODE REVIEW

**Comment by gorouflex** [comment]
my code kinda bad but i hope it still can work w everyone

**Comment by gorouflex** [comment]
@MrLoLf the serects variable can only set on GitHub repo settings and no body can access to that

**Comment by MrLoLf** [comment]
I'll try to figure a solution, so it can be run with both maybe a bool that has true or false in it, so you can select it in the code when downloading it to false manually, that the password and email input is required.

**Comment by gorouflex** [comment]
> I'll try to figure a solution, so it can be run with both maybe a bool that has true or false in it, so you can select it in the code when downloading it to false manually, that the password and email input is required.

I forgot about thía GitHub Actions doesn't have the console input so we cannot do that except separate the main.py into 2 parts or link to my repo...

**Comment by gorouflex** [comment]
@MrLoLf done it should work, but i need more 7mb to gain access to the lucky pot

**Comment by gorouflex** [comment]
I set the `IsGit` env from GitHub if it's is 1 (workflow set) it will take email and password from serect variable, and work normal w docker if is 0 (none)

**Comment by gorouflex** [comment]
@MrLoLf Done , both Docker and GitHub Actions

**Comment by MrLoLf** [comment]
Thank you I'll test this shortly today. And if everything goes to plan I'll merge it. Thanks a lot.

**Review by MrLoLf — APPROVED** [review]

**Pull request merged**
